# Generated by Django 5.0.4 on 2024-10-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address_location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('google_map_address', models.URLField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('menu_name', models.CharField(max_length=255)),
                ('menu_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=255)),
                ('system_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_mail', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=15)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('food_gst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('room_gst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('joined_date', models.DateTimeField()),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hotelowner')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField()),
                ('menu_name', models.CharField(max_length=255)),
                ('menu_url', models.CharField(max_length=255)),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parentmenus')),
                ('system_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.systeminfo')),
            ],
        ),
        migrations.AddField(
            model_name='parentmenus',
            name='system_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.systeminfo'),
        ),
        migrations.CreateModel(
            name='PermissionsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usertype'),
        ),
    ]
